name: Unittest CI Pipeline

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        id: run_tests
        run: |
          set +e
          python -m unittest discover -v > result.log 2>&1
          exit_code=$?
          echo "env_exit_code=$exit_code" >> $GITHUB_ENV
          echo "env_log=$(cat result.log)" >> $GITHUB_ENV
          exit "$exitcode"

      - name: Notify Slack
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_KEVIN_TEST }}
        run: |
          if [[ $env_exit_code -ne 0 ]]; then
            STATUS="FAILED"
            COLOR="danger"
          else
            STATUS="PASSED"
            COLOR="good"
          fi

          PAYLOAD="{
            \"text\": \"CI Pipeline Test Result: $STATUS\",
            \"attachments\": [
              {
                \"text\": \"Test Log: $env_log\",
                \"color\": \"$COLOR\"
              }
            ]
          }"

          curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" $SLACK_WEBHOOK_URL
