name: Unittest CI Pipeline

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          set +e
          python -m unittest discover -v > result.txt 2>&1
          exit_code=$?
          echo "env_exit_code=$exit_code" >> $GITHUB_ENV
          awk '/==============/,/FAILED /' result.txt > fail_error.txt
          exit $exit_code

      - name: Set text
        id: set_text
        run: |
          if [[ $env_exit_code -eq 0 ]]; then
            text=":white_check_mark: Unit tests passed"
          else
            text=":no_entry: Unit tests failed"
          fi
          echo "text=$text" >> "$GITHUB_OUTPUT"
          sudo apt-get install -y jq
          echo "log=$(cat fail_error.txt | jq -Rs .)" >> "$GITHUB_OUTPUT"
        if: always()

      - name: Slack notification
        uses: 8398a7/action-slack@v3.16.2
        with:
          status: ${{ job.status }}
          text: ${{ steps.set_text.outputs.text }}
          job_name: Run unit tests
          author_name: Run unit tests
          fields: repo,author,workflow,job,took,pullRequest
          custom_payload: |
            {
              attachments: [
                {
                  color: '${{ job.status }}' === 'success' ? 'good' : 'danger',
                  text: ${{ steps.set_text.outputs.log }}
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_KEVIN_TEST }}
        if: always()
