name: Unittest CI Pipeline

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        id: run_tests
        run: |
          python -m unittest discover -v > result.log
          exit_code=$?
          echo "::set-output name=exit_code::$exit_code"
          echo "::set-output name=log::$(cat result.log)"

      - name: Notify Slack
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_KEVIN_TEST }}
        run: |
          if [ ${{ steps.run_tests.outputs.exit_code }} -ne 0 ]; then
            STATUS="FAILED"
          else
            STATUS="PASSED"
          fi

          PAYLOAD="{
            \"text\": \"CI Pipeline Test Result: $STATUS\",
            \"attachments\": [
              {
                \"text\": \"${{ steps.run_tests.outputs.log }}\",
                \"color\": \"${{ steps.run_tests.outputs.exit_code }}\" == "0" ? "good" : "danger"
              }
            ]
          }"

          curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" $SLACK_WEBHOOK_URL
